"""Render a before/after-TTT showcase JSON into a self-contained HTML page.

Input schema (showcase_report.json, produced on the GPU box):
{
  "<task_id>": {
    "train": [[input_grid, output_grid], ...],
    "test_input": grid, "test_output": grid,
    "before": grid | null, "before_solved": bool,
    "after": grid | null, "after_solved": bool,
    "adapt_seconds": float
  }, ...
}
Grids are lists of lists of ints 0-9 (standard ARC palette).

Usage: python demo/render_demo.py showcase_report.json demo/adaptation_demo.html
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

PALETTE = (
    "#000000", "#0074D9", "#FF4136", "#2ECC40", "#FFDC00",
    "#AAAAAA", "#F012BE", "#FF851B", "#7FDBFF", "#870C25",
)


def grid_svg(grid: list[list[int]] | None, cell: int = 14) -> str:
    if not grid:
        return "<div class='missing'>no prediction</div>"
    rows, cols = len(grid), len(grid[0])
    cells = []
    for r, row in enumerate(grid):
        for c, value in enumerate(row):
            cells.append(
                f"<rect x='{c * cell}' y='{r * cell}' width='{cell}' "
                f"height='{cell}' fill='{PALETTE[value]}' "
                f"stroke='#333' stroke-width='0.5'/>"
            )
    return (
        f"<svg width='{cols * cell}' height='{rows * cell}' "
        f"viewBox='0 0 {cols * cell} {rows * cell}'>{''.join(cells)}</svg>"
    )


def render(showcase: dict, out_path: Path) -> None:
    sections = []
    for task_id, entry in showcase.items():
        train_html = "".join(
            f"<div class='pair'><div>{grid_svg(pair[0])}<label>input</label></div>"
            f"<div class='arrow'>→</div>"
            f"<div>{grid_svg(pair[1])}<label>output</label></div></div>"
            for pair in entry["train"]
        )
        before_class = "good" if entry.get("before_solved") else "bad"
        after_class = "good" if entry.get("after_solved") else "bad"
        before_tag = "correct" if entry.get("before_solved") else "wrong"
        after_tag = "correct" if entry.get("after_solved") else "wrong"
        seconds = entry.get("adapt_seconds")
        seconds_note = (
            f" after {seconds:.0f}s of adaptation on one commodity GPU"
            if seconds
            else ""
        )
        sections.append(f"""
<section>
  <h2>Unseen task <code>{html.escape(task_id)}</code></h2>
  <h3>The model sees these demonstrations</h3>
  <div class='train'>{train_html}</div>
  <h3>…and must answer this</h3>
  <div class='pair'><div>{grid_svg(entry["test_input"])}<label>test input</label></div>
  <div class='arrow'>→</div>
  <div>{grid_svg(entry["test_output"])}<label>true answer (hidden from model)</label></div></div>
  <h3>Same 4B model, before vs after test-time adaptation{seconds_note}</h3>
  <div class='compare'>
    <div class='{before_class}'>{grid_svg(entry.get("before"))}<label>before adaptation — {before_tag}</label></div>
    <div class='{after_class}'>{grid_svg(entry.get("after"))}<label>after adaptation — {after_tag}</label></div>
  </div>
</section>""")

    page = f"""<meta charset='utf-8'>
<title>Adaptation demo — same model, minutes apart</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto;
         background: #fafafa; color: #1a1a1a; padding: 0 1rem; }}
  h1 {{ font-size: 1.6rem; }} h2 {{ margin-top: 2.5rem; }}
  h3 {{ color: #555; font-weight: 500; }}
  .pair, .compare {{ display: flex; gap: 1.2rem; align-items: center;
                     flex-wrap: wrap; margin: .8rem 0; }}
  .train {{ display: flex; gap: 2rem; flex-wrap: wrap; }}
  .arrow {{ font-size: 1.4rem; color: #888; }}
  label {{ display: block; font-size: .78rem; color: #666; margin-top: .3rem; }}
  .good svg {{ outline: 3px solid #2ECC40; }} .good label {{ color: #1a7a2e; font-weight: 600; }}
  .bad svg {{ outline: 3px solid #FF4136; }} .bad label {{ color: #b32d22; font-weight: 600; }}
  .missing {{ color: #b32d22; font-style: italic; }}
  footer {{ margin-top: 3rem; font-size: .8rem; color: #777; }}
</style>
<h1>Same small model. Minutes apart. The difference is adaptation.</h1>
<p>Each task below is from the public ARC-AGI-2 evaluation set — never seen
in training. "Before" is the model's answer as-is; "after" is the same
model following per-task test-time training on the demonstrations alone.</p>
{''.join(sections)}
<footer>All predictions generated by the arc-ttt harness; raw run data in
experiments/. Nothing hand-edited.</footer>
"""
    out_path.write_text(page)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    render(json.loads(Path(sys.argv[1]).read_text()), Path(sys.argv[2]))
